-- sql
-- `narayana/src/main/resources/sql/init-orders.sql`
-- Leave empty or add sample data if needed, Hibernate creates `customer_order`
-- Example:
-- INSERT INTO customer_order (item_code, requested_quantity, status) VALUES ('ITEM_A', 1, 'CREATED');
